In [48]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [49]:
df.drop(['Name',"PassengerId",'SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [50]:
target = df.Survived
inputs = df.drop('Survived',axis='columns')

In [51]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [52]:
final = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250

In [53]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [54]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [55]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(7)

   Pclass     Sex        Age     Fare
0       3    male  22.000000   7.2500
1       1  female  38.000000  71.2833
2       3  female  26.000000   7.9250
3       1  female  35.000000  53.1000
4       3    male  35.000000   8.0500
5       3    male  29.699118   8.4583
6       1    male  54.000000  51.8625

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(inputs,target,test_size=0.3)

In [57]:
len(X_train)

623

In [58]:
len(X_test)

268

In [59]:
len(inputs)

891

In [60]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [61]:
model.fit(X_train,y_train)

ValueError: could not convert string to float: 'male'

In [ ]:
model.score(X_test,y_test)

0.667910447761194

In [ ]:
X_test[:10]

     Pclass        Age     Fare
340       2   2.000000  26.0000
85        3  33.000000  15.8500
335       3  29.699118   7.8958
433       3  17.000000   7.1250
728       2  25.000000  26.0000
97        1  23.000000  63.3583
855       3  18.000000   9.3500
539       1  22.000000  49.5000
99        2  34.000000  26.0000
76        3  29.699118   7.8958

In [ ]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0])